### PR TITLE
add CMD

### PR DESCRIPTION
**Pull request by okrasn**

### CODE REVIEW

**Comment by uwx** [comment]
Thanks, but [Batch](https://github.com/knightking100/hello-worlds/blob/master/examples/MS-DOS_Batch.bat) has already been done. You can still get the shirt though :P

**Comment by okrasn** [comment]
@uwx if so then you should drop duplication of **javascript**:
* [CoffeeScript](https://github.com/knightking100/hello-worlds/blob/master/examples/CoffeeScript.coffee)
* [TypeScript](https://github.com/knightking100/hello-worlds/blob/master/examples/TypeScript.ts)

[**Pascal**](https://github.com/knightking100/hello-worlds/blob/master/examples/Pascal.pas):
* [Delphi](https://github.com/knightking100/hello-worlds/blob/master/examples/Delphi.dpr)

and so on.. :)

**Comment by uwx** [comment]
But CoffeeScript and TypeScript are dialects of JavaScript. CMD is just another name for Batch (which is probably incorrect, CMD is the name of the command processor, which was COMMAND.COM in the 16-bit era, the language name is actually Batch), they are completely the same thing (if anything, one is a newer version of the other, but the differences are extremely subtle, like support for extended file paths.)

A JavaScript developer can't simply pick up a CoffeeScript file and grasp the syntax if they haven't had experience with languages like Ruby beforehand, whereas an experienced Batch user probably can't tell you the difference between "MS-DOS Batch" and "CMD."

**Comment by okrasn** [comment]
If continue your thout that JS dev can't easy go CoffeScript and looking on defined examples avery JS dev will say that he/she TypeScript and CoffeScript dev. No dialects specific thing defined in examples. All examples are just JS code. The same with Delphi and Pascal.

If so I can easy create two pull requests with SASS and LESS that will be copy of CSS, agree? :)

**Pull request closed without merging**
