### PR TITLE
Added Hello World in LOLCODE & Racket

### PR DESCRIPTION
**Pull request by TheDreamSaver**
Added Hello World in LOLCODE
HAI_WORLD.lol

### CODE REVIEW

**Comment by knightking100** [comment]
Invalid

**Comment by TheDreamSaver** [comment]
May I know the reason why?
It's a legitimate programming language.
lolcode.org
https://en.wikipedia.org/wiki/LOLCODE

**Comment by TheDreamSaver** [comment]
Also added Racket.rkt
https://docs.racket-lang.org/guide/intro.html

**Comment by cjsimon** [comment]
The contribution guide says "only one new Hello World per pull request."

**Comment by TheDreamSaver** [comment]
It was termed invalid. When I first committed with only 1 Hello World.
So I put up two.

**Pull request merged**
