### PR TITLE
Commandline File cmd

### PR DESCRIPTION
**Pull request by HpotsirhcH**

### CODE REVIEW

**Comment by uwx** [comment]
The name of the language is Batch, CMD is the interpreter. Please update your pull request.

**Comment by HpotsirhcH** [comment]
Updatet to Batch.cmd

**Comment by uwx** [comment]
You renamed it, but it's in the wrong letter folder. Move it to the B folder, and capitalize the first letter of the name.

**Comment by uwx** [comment]
Almost there, but you should rename it to .bat and add `_2` to the name so it matches the other example.

**Comment by HpotsirhcH** [comment]
Is this worthy? I think you dont need two bat files? I added this PR due to the fact there is the "filetype" .cmd. It is nearly the same but still a little bit different.

The differences between .CMD and .BAT as far as CMD.EXE is concerned are: With extensions enabled, PATH/APPEND/PROMPT/SET/ASSOC in .CMD files will set ERRORLEVEL regardless of error. .BAT sets ERRORLEVEL only on errors.
https://stackoverflow.com/questions/148968/windows-batch-files-bat-vs-cmd

**Comment by uwx** [comment]
Well, I'll take it. Thanks!

**Pull request merged**
