### PR TITLE
ADD ALGOL Hello World!

### PR DESCRIPTION
**Pull request by MadhavBahlMD**
Add ALGOL Hello World

### CODE REVIEW

**Comment by MadhavBahlMD** [comment]
Add MATLAB Hello World! #1

**Comment by knightking100** [comment]
Invalid

**Comment by MadhavBahlMD** [comment]
Removed MATLAB.m
ALGOL Hello World Still There, Requested Changes Done 💯

**Comment by MadhavBahlMD** [comment]
Removed Readme.txt

**Comment by MadhavBahlMD** [comment]
Hey @knightking100  can you please add hacktoberfest label to my pull request, i am not able to do so.

**Pull request merged**
