### PR TITLE
Add Delphi Hello World

### PR DESCRIPTION
**Pull request by Alastifer**
reference issue #1

### CODE REVIEW

**Comment by knightking100** [comment]
Only one language per pull request (sorry, just put in Contributing.Md)
Also, please reference issue 1 (you can see how in #4 )

**Comment by knightking100** [comment]
Java Hello World already made in #2

**Comment by Alastifer** [comment]
@knightking100 It's not Java. It's Delphi

**Comment by knightking100** [comment]
Ok, got it

**Pull request merged**
